#!/bin/sh
# -*- sh -*-

: << =cut

=head1 NAME

slurm_cpus_active - Plugin to measure the number of active cpus in SLURM queue.

=head1 NOTES

Shows the number of CPUs in use by slurm running jobs.

=head1 AUTHOR

Contributed by Rael Garcia Arnes (raelga@gmail.com)

=head1 LICENSE

This program is free software: you can redistribute it and/or modify
it under the terms of the GNU General Public License as published by
the Free Software Foundation, either version 3 of the License, or
(at your option) any later version.

This program is distributed in the hope that it will be useful,
but WITHOUT ANY WARRANTY; without even the implied warranty of
MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
GNU General Public License for more details.

You should have received a copy of the GNU General Public License 
along with this program.  If not, see <http://www.gnu.org/licenses/>.

=head1 MAGIC MARKERS

#%# family=auto
#%# capabilities=autoconf

=cut

. $MUNIN_LIBDIR/plugins/plugin.sh

export SLURM_CLUSTERS=${0##*slurm_cpus_active_}
export PATH=$PATH:/usr/local/slurm/current/sbin:/usr/local/slurm/current/bin

case $1 in
    autoconf)
        echo yes 
        exit 0
        ;;

    config)
        echo graph_title "${SLURM_CLUSTERS}: CPUs in use in slurm queue"
        echo graph_vlabel "${SLURM_CLUSTERS}: CPUs"
        echo slurm_cpus.label "${SLURM_CLUSTERS}: CPUs"
        echo graph_category Slurm
        echo graph_info "${SLURM_CLUSTERS}: Number of cpus in use for the jobs enqueued in running state on slurm"
        exit 0
        ;;
    esac

squeue -o "%C" -tR | awk 'BEGIN {s=0} {s+=$1} END {printf "slurm_cpus.value  %g\n", s}'
